test('app.call  - parsedCall object', function () {
  var stub = createStub(app, 'exec')
  var testElement = createElement('div')
  app.call('func:#' + testElement.id + ':[value]')
  assertIsObject(stub.get.element).desc('element is object')
  assertEqual(stub.get.func, 'func').desc('func name')
  assertEqual(stub.get.value, 'value').desc('value')
  assertFalse(stub.get.attribute).desc('attribute name')
  assertFalse(stub.get.hasAttribute).desc('has attribute')
  assertFalse(stub.get.hasSubAttribute).desc('has sub attribute')
  assertFalse(stub.get.subElement).desc('has sub element')
})

test('app.call - parsedCall object', function () {
  var stub = createStub(app, 'exec')
  var testElement = createElement('div')
  app.call('func:#' + testElement.id + '.attribute:[value]')
  assertIsObject(stub.get.element).desc('element is object')
  assertEqual(stub.get.func, 'func').desc('func name')
  assertEqual(stub.get.value, 'value').desc('value')
  assertEqual(stub.get.attribute, 'attribute').desc('attribute name')
  assertTrue(stub.get.hasAttribute).desc('has attribute')
  assertFalse(stub.get.hasSubAttribute).desc('has sub attribute')
  assertFalse(stub.get.subElement).desc('sub element')
})